### ISSUE TITLE
Calendar doesn't display

### ISSUE THREAD

**Issue by Critter** [omnia-digital/livewire-calendar#16]
Just using the values from the readme, I get no errors, but nothing displays either. Any suggestions on where to start looking?

**Comment by joshtorres** [comment]
Did you add the component to a specific view? If you added the component and still get nothing, I would add https://github.com/barryvdh/laravel-debugbar and see if you can figure out what is happening there or check the laravel logs.
![image](https://github.com/omnia-digital/livewire-calendar/assets/5092957/4dc418ae-4426-44fe-ab3e-73a6542b5787)

**Comment by ndynamite** [comment]
It's really strange. I'm getting the exact same thing. 

There are no errors, and nothing reported in Telescope. The livewireScripts and livewireCalendarScripts are included fine. 

It seems like its an issue that has occurred for other users before:

Here:
https://github.com/asantibanez/livewire-calendar/issues/31

And here:
https://github.com/omnia-digital/livewire-calendar/issues/12

I just can't figure it out at all. 

@Critter did you manage to find a solution?

**Comment by joshtorres** [comment]
oh you're right, thanks for reminding me of that. So it looks like in that instance he made a child component of LivewireCalendar and then never called the parent::render(). So you can render your own child component in 2 ways:
- set the $this->calendarView to your view component and then call parent::render()
- override the render() method and make sure to include all of the parameters. 
![image](https://github.com/omnia-digital/livewire-calendar/assets/5092957/10d589db-7d31-45c7-8fda-7f2ba5287854)

Let me know if that helps

**Comment by Critter** [comment]
@joshtorres  I'm still quite new to Laravel, and still not able to suss it out. If I use the code above, I throw an error: 

Property [$id] not found on component: [appointments-calendar]

on `'componentId' => $this->id,`

**Comment by joshtorres** [comment]
@Critter ok thanks for pointing that out. It looks like the new version of livewire is using a different way of retrieving the component Id. I just updated the LivewireCalendar component so now it should work with either version of livewire.
Also, I realized that you don't need the render method at all in your child AppointmentsCalendar component.
It should look similar to this:
![image](https://github.com/omnia-digital/livewire-calendar/assets/5092957/cf2716bb-b49b-4b01-9171-8a51aee75358)

**Comment by Critter** [comment]
@joshtorres  perfect! that did it. I appreciate you taking the time to explain it.

/cc @ndynamite this sorted it.

**Comment by Critter** [comment]
@joshtorres Dude. that debug bar is some shit! Thanks for that also. 🙏🏻

**Comment by KhairulAzmi21** [comment]
<img width="1188" alt="Screenshot 2024-03-24 at 11 07 49" src="https://github.com/omnia-digital/livewire-calendar/assets/12378983/c4e569c2-715b-451a-b34b-f6d3a54180e1">

I getting plain component also . dont know how to fix this ..

**Comment by joshtorres** [comment]
No problem! Yeah Debugbar is amazing!
