### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by jordivela007** [omnia-digital/livewire-calendar#18]
I'm using this library and works properly, but the only thing is i can't use Drag and Drop.

The debugger show a jquery error in the call of this function onLivewireCalendarEventDrop:

window.Livewire.find(componentId).call('onEventDropped', eventId, year, month, day);

and the object to Drag is defined correctly
```bash
<div class="flex py-2">
        <div
                class="shadow p-2 border rounded bg-white mr-2"
                ondragstart="onLivewireCalendarEventDragStart(event, '9b5376c1-1375-4cfe-be24-6ef549a6dfdb')"
                draggable="true"
                name='9b5376c1-1375-4cfe-be24-6ef549a6dfdb'
                style="background-color:#E0BBE4;border-color:#E0BBE4;"
            >
                <p class="font-medium text-sm">
                    Diari
                </p>
                <p class="text-xs">
                    08:00-17:00
                </p>
                <button wire:click.stop="deleteEvent(9b5376c1-1375-4cfe-be24-6ef549a6dfdb)" type="button"
                    class="mt-2 inline-flex items-center px-2 py-1 border border-transparent text-xs leading-4 font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-50 focus:outline-none focus:border-indigo-300 focus:shadow-outline-indigo active:bg-indigo-200 transition ease-in-out duration-150">
                    Eliminar
                </button>
         </div>
</div>
```

**Comment by joshtorres** [comment]
Can you please post the error you are seeing?

**Comment by jordivela007** [comment]
events:2250 Uncaught TypeError: Cannot read properties of undefined (reading 'call').
Seems the problem is in the variable componentId. Its empty.
![image](https://github.com/omnia-digital/livewire-calendar/assets/19904616/cd660f6f-aa2d-4b7c-a46b-3a002fe880b2)

**Comment by jordivela007** [comment]
The problem with componentId is solved.
Is necessary to add the id in the blade

```bash
<div class="basis-20 box-border rounded-lg border-2 shadow-md cursor-pointer">
        <livewire:event-grid-component week-starts-at="1" before-calendar-view="livewire.events.before" id="calendar"/>
 </div>
```

But still show the same error:
![image](https://github.com/omnia-digital/livewire-calendar/assets/19904616/e348c770-d40d-4eac-a304-0c21844815b3)

**Comment by jordivela007** [comment]
I updaed to v301 and it's working!!! Thanks for all!!

**Comment by jordivela007** [comment]
I updaed to v301 and it's working!!! Thank you for all!!

**Comment by jordivela007** [comment]
I updaed to v301 and it's working!!! Thank you for all!!
