### ISSUE TITLE
  Could not find a matching version of package omnia-digital/livewire-calendar

### ISSUE THREAD

**Issue by joshtorres** [omnia-digital/livewire-calendar#5]
Reported by @yamakrane
composer require omnia-digital/livewire-calendar

Could not find a matching version of package omnia-digital/livewire-calendar. Check the package spelling, your version constraint an
d that the package is available in a stability which matches your minimum-stability (stable).

**Comment by yamakrane** [comment]
This is actually thrown by composer when I enter composer require omnia-digital/livewire-calendar

**Comment by joshtorres** [comment]
Ok fixed in release https://github.com/omnia-digital/livewire-calendar/releases/tag/2.2.1
Let me know if you still have any issues.
