### ISSUE TITLE
Laravel 10 with php 8.2.5

### ISSUE THREAD

**Issue by kasirye** [omnia-digital/livewire-calendar#7]
Hi, i have been previously using asantibanez/livewire-calendar, but it seems no one has been maintaining/updating it for a while. So after reading that you will be updating it, i decided to use omnia. 

Am trying to use calendars on my new laravel 10 with php version 8.2.5, but am unable to install omnia because of the php version. Any help?

**Comment by joshtorres** [comment]
Hey @kasirye sorry I'm not sure why but I never saw a notification for this. Yes I'll take a look at this.

**Comment by joshtorres** [comment]
Ok this has been fixed
